### ISSUE TITLE
Tracking issue for Document Symbol source

### ISSUE THREAD

**Issue by nhat-vo** [nvim-neo-tree/neo-tree.nvim#879]
As merged in #841, we now have an additional `document_symbol` source. This source is still rather simple, and more features will be added in the future. The original features are listed in the description of #841, and this issue will track additional features to be implemented.

- [ ] UI:
	- [ ] Follow cursor: just like "follow current file", always have the symbol I'm currently on selected.
- [ ] Commands
	- [ ] Hover docs
	- [ ] Call hierarchy 
	- [ ]  Fuzzy search/filter
- [ ] CoC Support (I don't use CoC, so if anyone would like to help with this, please feel free to do so 😅)
- [ ] Workspace symbols support #593 (as @cseickel mentioned, it would be better to finish the other features first before this)

**Comment by nhat-vo** [comment]
> Can we also throw support for [lspkind.nvim](https://github.com/onsails/lspkind.nvim) into this? I attempted to do this myself in `document_symbol.kinds` but `lspkind` doesn't return Highlight Groups (as far as I can tell) for the items so I don't have a great way to do this. It would be nice if we could simply pass something from `lspkind`  to update _just_ the icons, while letting the `document_symbol` source manage the Highlight Group

At first, I did try to use Lspkind's icons, but this plugin provides the icon for a different set of kinds ([Completion kinds](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion) vs. [Symbol kinds](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol)). So it's not very straightforward to add this. Instead, it is quite straightforward to just copy their symbols, modify them accordingly, and paste into your config.

> Edit: After reading #593, is my request the same as that?

I don't think so, #593's request is an integration between the `filesystem` and `documents_symbols` sources, rather than a icon config like this.

**Comment by nhat-vo** [comment]
> It _should_ be, but I don't know the appropriate highlight groups being used in the background (IE, it doesn't appear they are exposed). Which means that I have to set the icons and make my own highlight group for each icon.

Oh I see. Just to confirm, do you mean that the default highlight groups should be used when only the names are specified? If so, I think it should be quite an easy tweak - changing `tbl_extend` to `tbl_deep_extend`. I'll add it this weekend.

**Comment by miversen33** [comment]
Yes exactly! If a highlight group isn't provided, the default should be used.

**Comment by nhat-vo** [comment]
> Hi all, very glad to have this feature implemented, I just want to report that I get an error when selecting a document_symbol when the tree is shown in position current (in the same window as the file being edited):
> 
> E5108: Error executing lua: ....nvim/lua/neo-tree/sources/document_symbols/commands.lua:25: Cursor position outside buffer stack traceback: [C]: in function 'nvim_win_set_cursor' ....nvim/lua/neo-tree/sources/document_symbols/commands.lua:25: in function 'func' ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:782: in function <...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:780>
> 
> Thank you very much for this plugin, the best I found that can also work in split mode like netrw.

@tenllado Thanks for reporting the bug! Indeed I forgot the case when the buffer is changed in the window like when using `position=current` 😅. I'll push a fix this weekend for this.

**Comment by TLSingh1** [comment]
Hi, sorry if I'm not properly documenting this. Please let me know if there's any more info I can provider.

When enabling in sources and running ```:Neotree document_symbols``` I get the follwoing warning/error ```[Neo-tree WARN] Error rendering component name: ...vim/lua/neo-tree/sources/document_symbols/components.lua:37: attempt to index field 'extra'
 (a nil value)```
 
 Also can be see in the image here
 
![symbols2](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/89089655/aefc62f9-c727-45ed-a2fa-cf1d126457a0)

 Thanks again for making my favorite tree by far :pray:

**Comment by Curs3W4ll** [comment]
Same problem as you https://github.com/nvim-neo-tree/neo-tree.nvim/issues/879#issuecomment-1569661709

**Comment by Lazerbeak12345** [comment]
> > Can we also throw support for [lspkind.nvim](https://github.com/onsails/lspkind.nvim) into this? I attempted to do this myself in `document_symbol.kinds` but `lspkind` doesn't return Highlight Groups (as far as I can tell) for the items so I don't have a great way to do this. It would be nice if we could simply pass something from `lspkind`  to update _just_ the icons, while letting the `document_symbol` source manage the Highlight Group
> 
> At first, I did try to use Lspkind's icons, but this plugin provides the icon for a different set of kinds ([Completion kinds](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion) vs. [Symbol kinds](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol)). So it's not very straightforward to add this. Instead, it is quite straightforward to just copy their symbols, modify them accordingly, and paste into your config.

I've found a close match to be this:

```
local completion_kinds = require'lspkind'.symbol_map -- Completion-kinds:Document-kinds not a 1:1 map
...
document_symbols = { kinds = {
	File = { icon = completion_kinds.File, hl = "Tag" },
	Namespace = { icon = completion_kinds.Module, hl = "Include" },
	Package = { icon = "󰏖", hl = "Label" },
	Class = { icon = completion_kinds.Class, hl = "Include" },
	Property = { icon = completion_kinds.Property, hl = "@property" },
	Enum = { icon = completion_kinds.Enum, hl = "@number" },
	Function = { icon = completion_kinds.Function, hl = "Function" },
	String = { icon = completion_kinds.Text, hl = "String" },
	Number = { icon = completion_kinds.Value, hl = "Number" },
	Array = { icon = "󰅪", hl = "Type" },
	Object = { icon = "󰅩", hl = "Type" },
	Key = { icon = completion_kinds.Keyword, hl = "" },
	Struct = { icon = completion_kinds.Struct, hl = "Type" },
	Operator = { icon = completion_kinds.Operator, hl = "Operator" },
	TypeParameter = { icon = completion_kinds.TypeParameter, hl = "Type" },
	StaticMethod = { icon = completion_kinds.Method, hl = 'Function' }
} },
```

And concerning highlight groups, https://github.com/onsails/lspkind.nvim/issues/32

**Comment by nhat-vo** [comment]
@TLSingh1 @Curs3W4ll I have just pushed a fix in #972. Could you have a look to see if this fixes the issue?

**Comment by cseickel** [comment]
I actually merged it already, so you can just try out `main` as well.

**Comment by Curs3W4ll** [comment]
@nhat-vo Seems to fix the error message. Thank you!

But there is still a bug with the `add_blank_line_at_top` option.  
When set to true, nothing is displayed (see screenshots below)

`add_blank_line_at_top = true`
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/72013831/0dc7918a-a542-4a45-96e2-67d152ef3328)

`add_blank_line_at_top = false`
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/72013831/8f5129c4-aa60-443e-b3ec-d9cf1463cf97)

**Comment by nhat-vo** [comment]
@Curs3W4ll Sorry for the late reply. I have just pushed #1066, which fixes this issue. Have a look to see if it's gone!

**Comment by Curs3W4ll** [comment]
> @Curs3W4ll Sorry for the late reply. I have just pushed #1066, which fixes this issue. Have a look to see if it's gone!

Hey, no problem at all.  
Yep, this is now working well.  
Thank you!

**Comment by swaits** [comment]
Not sure if I should create new issues or post them here... I'll start here, LMK if you want new issues instead:

Based on the command: `<cmd>Neotree action=show source=document_symbols position=right reveal=true toggle=true<cr>`:

1. **bug:** "show" does not keep the focus in the current window, instead the new Neotree window is focused.
2. **feature?:** (this could be a bug, too). "reveal" is not working (this could be the same functionality as `follow_cursor`, but as a one off on init
3. **feature:** I think it might be pretty common that folks want these to always be in the "all nodes expanded" mode. I thought I wanted that, but I found that I like how it expands as I move through my code courtesy of `follow_cursor`

This is a really cool feature. I'm able to replace aerial now, and I'm always happy to load one less plugin.

**Comment by phreeza** [comment]
I'd be interested in taking a shot at call hierarchy. I don't have any experience with neovim development, so any pointers would be very appreciated.

**Comment by twio142** [comment]
Hi, I found this bug when doing `show_help` in `document_symbols`:

```
E5108: Error executing lua: ...ou/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua:22: attempt to index local 'block' (a nil value)
stack traceback:
        .../.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua:22: in function 'append'
        .../lazy/neo-tree.nvim/lua/neo-tree/sources/common/help.lua:62: in function 'show'
        ...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:886: in function <...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:883>
```

Not sure if something's wrong with my configurations.

**Comment by Kaiser-Yang** [comment]
The fixed size for pop-up is too abrupt, maybe a better way for auto ajust the size to fit the content.

Something like [lsp-saga](https://nvimdev.github.io/lspsaga/outline/)?
